/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.sistemacontable.vista;

import com.mycompany.sistemacontable.controlador.Controlador_All;

/**
 *
 * @author Usuario
 */
public class BuscarEmpleado extends javax.swing.JFrame {

    /**
     * Creates new form BuscarEmpleado
     */
    public BuscarEmpleado() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        nombreE = new javax.swing.JLabel();
        codigoE = new javax.swing.JLabel();
        xxEmpleado = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txEmpleado = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        apellidoE = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Book Antiqua", 1, 18)); // NOI18N
        jLabel1.setText("EMPLEADO:");

        nombreE.setFont(new java.awt.Font("Garamond", 0, 18)); // NOI18N

        codigoE.setFont(new java.awt.Font("Garamond", 0, 18)); // NOI18N

        xxEmpleado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                xxEmpleadoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                xxEmpleadoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                xxEmpleadoKeyTyped(evt);
            }
        });

        txEmpleado.setModel(new Tabla_Empleados());
        txEmpleado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txEmpleadoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(txEmpleado);

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton1.setText("ENVIAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        apellidoE.setFont(new java.awt.Font("Garamond", 0, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 589, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 638, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(xxEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(codigoE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(nombreE, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(apellidoE, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(xxEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(codigoE, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nombreE, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(apellidoE, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jButton1)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        VtnBalanceHaber vtnHaber = new VtnBalanceHaber();
       vtnHaber.setDatoCE(codigoE.getText());
       vtnHaber.setDatoNE(nombreE.getText());
       vtnHaber.setDatoAE(apellidoE.getText());
       vtnHaber.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txEmpleadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txEmpleadoMouseClicked
        // TODO add your handling code here:
        codigoE.setText((String) txEmpleado.getValueAt(txEmpleado.getSelectedRow(), 4));
        nombreE.setText((String) txEmpleado.getValueAt(txEmpleado.getSelectedRow(), 1));
        apellidoE.setText((String) txEmpleado.getValueAt(txEmpleado.getSelectedRow(), 2));
    }//GEN-LAST:event_txEmpleadoMouseClicked

    private void xxEmpleadoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_xxEmpleadoKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_xxEmpleadoKeyPressed

    private void xxEmpleadoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_xxEmpleadoKeyReleased
        // TODO add your handling code here:
        metodo();
    }//GEN-LAST:event_xxEmpleadoKeyReleased

    private void xxEmpleadoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_xxEmpleadoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_xxEmpleadoKeyTyped

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel apellidoE;
    private javax.swing.JLabel codigoE;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nombreE;
    private javax.swing.JTable txEmpleado;
    private javax.swing.JTextField xxEmpleado;
    // End of variables declaration//GEN-END:variables

    private void metodo(){
        imprimirCodigo(xxEmpleado.getText());
        
        txEmpleado.setModel(new Tabla_Empleados (new Controlador_All().generarC(xxEmpleado.getText())));
    }

    void imprimirCodigo(String codigo) {

        for (int i = 0; i < new Controlador_All().generarC(codigo).size(); i++) {
            System.out.println(new Controlador_All().generarC(codigo).get(i));
            System.out.println("--------------------------------------");

        }
    }
}
