/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.sistemacontable.vista;

import com.mycompany.sistemacontable.controlador.Controlador_All;
import java.awt.BorderLayout;
import javax.swing.JDesktopPane;

/**
 *
 * @author Usuario
 */
public class MenuVtn extends javax.swing.JFrame {

    /**
     * Creates new form MenuVtn
     */
     //private JDesktopPane escritorio;
    RegistrarCliente reg = new RegistrarCliente();
     ActualizarCliente act = new ActualizarCliente();
     RegistrarProveedor regPro = new RegistrarProveedor();
      ActualizarProveedor actPro = new ActualizarProveedor();
      ActualizarEmpleado actEmp = new ActualizarEmpleado();
      RegistrarEmpleado regEmp = new RegistrarEmpleado();
      Historial_Balance hisBal=new Historial_Balance();
      
     
    

    public MenuVtn() {
         initComponents();
        setLocationRelativeTo(null);
        getContentPane().setLayout(new BorderLayout());
		
                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        Cliente = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        Proveedor = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        Empleado = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        Balance = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SISTEMA BALANCE");

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1686, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1080, Short.MAX_VALUE)
        );

        Cliente.setText("Cliente");

        jMenuItem1.setText("Registrar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        Cliente.add(jMenuItem1);

        jMenuItem2.setText("Actualizar");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        Cliente.add(jMenuItem2);

        jMenuBar1.add(Cliente);

        Proveedor.setText("Proveedor");

        jMenuItem3.setText("Registrar");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        Proveedor.add(jMenuItem3);

        jMenuItem4.setText("Actualizar");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        Proveedor.add(jMenuItem4);

        jMenuBar1.add(Proveedor);

        Empleado.setText("Empleado");

        jMenuItem6.setText("Registrar");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        Empleado.add(jMenuItem6);

        jMenuItem7.setText("Actualizar ");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        Empleado.add(jMenuItem7);

        jMenuBar1.add(Empleado);

        Balance.setText("Balance");

        jMenuItem5.setText("Gestionar Balance");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        Balance.add(jMenuItem5);

        jMenuItem8.setText("Historial Balance");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        Balance.add(jMenuItem8);

        jMenuBar1.add(Balance);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
       
        
        this.escritorio.remove(act);
        this.escritorio.remove(  regPro);
        this.escritorio.remove(  actPro);
         this.escritorio.remove(  actEmp);
          this.escritorio.remove(  regEmp);
           
        if (reg.isClosed()) {

            this.escritorio.remove(reg);
            this.escritorio.add(reg);
        } else {
            this.escritorio.remove(reg);
            this.escritorio.add(reg);
        }

        reg.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
       
        this.escritorio.remove(reg);
        this.escritorio.remove(  regPro);
        this.escritorio.remove(  actPro);
         this.escritorio.remove(  actEmp);
          this.escritorio.remove(  regEmp);
          
      
                
       if (act.isClosed()) {

            this.escritorio.remove(act);
            this.escritorio.add(act);
        } else {
            this.escritorio.remove(act);
            this.escritorio.add(act);
        }
        act.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
         this.escritorio.remove(reg);
        this.escritorio.remove(  act);
          this.escritorio.remove(  actPro);
           this.escritorio.remove(  actEmp);
            this.escritorio.remove(  regEmp);
     
        
       if (regPro.isClosed()) {

            this.escritorio.remove(regPro);
            this.escritorio.add(regPro);
        } else {
            this.escritorio.remove(regPro);
            this.escritorio.add(regPro);
        }

      
        regPro.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
         this.escritorio.remove(reg);
        this.escritorio.remove(  act);
        this.escritorio.remove(  regPro);
         this.escritorio.remove(  actEmp);
          this.escritorio.remove(  regEmp);
      
       if (actPro.isClosed()) {

            this.escritorio.remove(actPro);
            this.escritorio.add(actPro);
        } else {
            this.escritorio.remove(actPro);
            this.escritorio.add(actPro);
        }
        actPro.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
     
        VtnBalanceGeneral vtnBalGen = new VtnBalanceGeneral();
        //escritorio.add(vtnBalGen);
        vtnBalGen.setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
        
        this.escritorio.remove(reg);
        this.escritorio.remove(  act);
        this.escritorio.remove(  regPro);
        this.escritorio.remove(  actPro);
         this.escritorio.remove(  regEmp);
          
       if (actEmp.isClosed()) {

            this.escritorio.remove(actEmp);
            this.escritorio.add(actEmp);
        } else {
            this.escritorio.remove(actEmp);
            this.escritorio.add(actEmp);
        }
        actEmp.setVisible(true);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        
        this.escritorio.remove(reg);
        this.escritorio.remove(  act);
        this.escritorio.remove(  regPro);
        this.escritorio.remove(  actPro);
         this.escritorio.remove(  actEmp);
         
       if (regEmp.isClosed()) {

            this.escritorio.remove(regEmp);
            this.escritorio.add(regEmp);
        } else {
            this.escritorio.remove(regEmp);
            this.escritorio.add(regEmp);
        }
        regEmp.setVisible(true);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
        
        hisBal.setVisible(true);
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Balance;
    private javax.swing.JMenu Cliente;
    private javax.swing.JMenu Empleado;
    private javax.swing.JMenu Proveedor;
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    // End of variables declaration//GEN-END:variables
}
