/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.sistemacontable.vista;

import com.mycompany.sistemacontable.controlador.Controlador_All;
import com.mycompany.sistemacontable.controlador.Empleado_Controlador;
import com.mycompany.sistemacontable.controlador.Haber_Controlador;
import com.mycompany.sistemacontable.controlador.Persona_Controlador;
import com.mycompany.sistemacontable.controlador.Proveedor_Controlador;
import com.mycompany.sistemacontable.modelo.Empleado;
import com.mycompany.sistemacontable.modelo.Haber;
import com.mycompany.sistemacontable.modelo.Persona;
import com.mycompany.sistemacontable.modelo.Proveedor;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class VtnBalanceHaber extends javax.swing.JFrame {

    /**
     * Creates new form VtnHaber
     */
    Proveedor pro = null;
    Proveedor prot = null;
    Empleado emp = null;
    Empleado empt = null;
    Persona per = null;
    private String nombreProveedor;
    private String apellidoProveedor;
    private String rucProveedor;
    private String codigoEmpleado;
    private String nombreEmpleado;
    private String apellidoEmpleado;

    public VtnBalanceHaber() {
        initComponents();
        metodo();
    }

    public void setDatoNP(String datoNP) {
        this.nombreProveedor = datoNP;
        nombrepr.setText(datoNP);
    }

    public void setDatoAP(String datoAP) {
        this.apellidoProveedor = datoAP;
        apellidopr.setText(datoAP);
    }

    public void setDatoRP(String datoRP) {
        this.rucProveedor = datoRP;
        rucpr.setText(datoRP);
    }

    public void setDatoCE(String datoCE) {
        this.codigoEmpleado = datoCE;
        codigoemp.setText(datoCE);
    }

    public void setDatoNE(String datoNE) {
        this.nombreEmpleado = datoNE;
        nombremp.setText(datoNE);
    }

    public void setDatoAE(String datoAE) {
        this.apellidoEmpleado = datoAE;
        apellidoemp.setText(datoAE);
    }

    private void metodo() {
        txHaber.setModel(new Tabla_Haber(new Controlador_All().reflejarHaber()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        nombremp = new javax.swing.JLabel();
        apellidoemp = new javax.swing.JLabel();
        jToggleButton2 = new javax.swing.JToggleButton();
        jLabel3 = new javax.swing.JLabel();
        comboPago = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        valor = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        detalle = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txHaber = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jToggleButton3 = new javax.swing.JToggleButton();
        jLabel6 = new javax.swing.JLabel();
        nombrepr = new javax.swing.JLabel();
        rucpr = new javax.swing.JLabel();
        apellidopr = new javax.swing.JLabel();
        codigoemp = new javax.swing.JLabel();
        administrativo = new javax.swing.JLabel();

        jLabel2.setFont(new java.awt.Font("Book Antiqua", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("EMPLEADO: ");

        jToggleButton1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jToggleButton1.setText("BUSCAR");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        nombremp.setFont(new java.awt.Font("Garamond", 0, 18)); // NOI18N
        nombremp.setText(" ");

        apellidoemp.setFont(new java.awt.Font("Garamond", 0, 18)); // NOI18N

        jToggleButton2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jToggleButton2.setText("BUSCAR");
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Book Antiqua", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("TIPO DE PAGO: ");

        comboPago.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        comboPago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione --", "Efectivo", "Tarjeta de Credito", "Transferencia Bancaria", "Tarjeta de Debito" }));
        comboPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboPagoActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Book Antiqua", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("VALOR: ");

        valor.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        valor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valorActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Book Antiqua", 1, 18)); // NOI18N
        jLabel5.setText("DETALLE:");

        txHaber.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(txHaber);

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton1.setText("REFLEJAR");

        jToggleButton3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jToggleButton3.setText("AGREGAR");
        jToggleButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton3ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Book Antiqua", 1, 18)); // NOI18N
        jLabel6.setText("PROVEEDOR:");

        nombrepr.setFont(new java.awt.Font("Garamond", 0, 18)); // NOI18N

        rucpr.setFont(new java.awt.Font("Garamond", 0, 18)); // NOI18N

        apellidopr.setFont(new java.awt.Font("Garamond", 0, 18)); // NOI18N

        codigoemp.setFont(new java.awt.Font("Garamond", 0, 18)); // NOI18N
        codigoemp.setText(" ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(detalle))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(comboPago, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(codigoemp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(nombremp, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(apellidoemp, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rucpr, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(nombrepr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(apellidopr, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(valor)
                            .addComponent(jToggleButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jToggleButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jToggleButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE))))
                .addGap(15, 15, 15))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(administrativo, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(administrativo)
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nombrepr, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(apellidopr, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rucpr, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(codigoemp, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(nombremp, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(apellidoemp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jToggleButton1)
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jToggleButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(comboPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 15, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(valor, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(detalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton3))
                .addGap(10, 10, 10)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(jButton1)
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void valorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valorActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
        BuscarProveedor busPro = new BuscarProveedor();
        busPro.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        // TODO add your handling code here:
        BuscarEmpleado busEm = new BuscarEmpleado();
        busEm.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void jToggleButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton3ActionPerformed
        // TODO add your handling code here:
        String code = "00000";
        String rucpro = "001";
        prot = new Proveedor_Controlador().getProveedor(1);
        empt = new Empleado_Controlador().getEmpleado(1);
        /*
        per = new Persona_Controlador().getPersona(pro.getPersona().getId());
        per = new Persona_Controlador().getPersona(emp.getPersona().getId());
        per = new Persona_Controlador().getPersona(prot.getPersona().getId());
        per = new Persona_Controlador().getPersona(empt.getPersona().getId());
         */
        Haber hab = new Haber();
        String pago = (String) comboPago.getSelectedItem();
        /*
        if (apellidoemp.getText().equals("")) {
            pro = new Proveedor_Controlador().getProveedor(new Controlador_All().id_perP(rucpr.getText()));
            if (pago.equals("Seleccion --")) {
                JOptionPane.showMessageDialog(null, "No ha seleccionado ninguna opcion");
            } else {
                hab.setProveedor(pro);
                hab.setEmpleado(empt);
                hab.setId(0);
                hab.setTipoBeneficiario("Proveedor");
                hab.setTipoPago(comboPago.getSelectedItem().toString());
                hab.setValor(Double.parseDouble(valor.getText()));
                hab.setDetalle(detalle.getText());
                Haber_Controlador habC = new Haber_Controlador();
                habC.crear(hab);
                System.out.println("Resultado de Empleado");
                System.out.println(nombremp.getText());
                System.out.println("*********RESULTADO DE EMPLEADO**********");
                System.out.println(empt);
                limpiar();
                JOptionPane.showMessageDialog(null, "Se hizo un pago a un proveedor");
            }

        }else if (nombrepr.getText().equals("")) {
            emp = new Empleado_Controlador().getEmpleado(new Controlador_All().id_perEC(codigoemp.getText()));
            if (pago.equals("Seleccion --")) {
                JOptionPane.showMessageDialog(null, "No ha seleccionado ninguna opcion");
            } else { 
                hab.setEmpleado(emp);
                hab.setProveedor(prot);
                hab.setId(0);
                hab.setTipoBeneficiario("Empleado");
                hab.setTipoPago(comboPago.getSelectedItem().toString());
                hab.setValor(Double.parseDouble(valor.getText()));
                hab.setDetalle(detalle.getText());
                Haber_Controlador habC = new Haber_Controlador();
                habC.crear(hab);
                System.out.println("Resultado de Proveedor");
                System.out.println(nombrepr.getText());
                System.out.println("*********RESULTADO DE PROVEEDOR**********");
                System.out.println(empt);
                limpiar();
                JOptionPane.showMessageDialog(null, "Se hizo pago a un empleado");
            }

        } else if (administrativo.getText().equals("")) {
                   prot = new Proveedor_Controlador().getProveedor(1);
                   empt = new Empleado_Controlador().getEmpleado(1);
            if (pago.equals("Seleccion --")) {
                JOptionPane.showMessageDialog(null, "No ha seleccionado ninguna opcion");
            } else {
                hab.setId(0);
                hab.setProveedor(prot);
                hab.setEmpleado(empt);
                hab.setTipoBeneficiario("Administrativo");
                hab.setTipoPago(comboPago.getSelectedItem().toString());
                hab.setValor(Double.parseDouble(valor.getText()));
                hab.setDetalle(detalle.getText());
                Haber_Controlador habC = new Haber_Controlador();
                habC.crear(hab);
                System.out.println("Resultado de Empleado");
                System.out.println(nombremp.getText());
                System.out.println("Resultado de Proveedor");
                System.out.println(nombrepr.getText());
                limpiar();
                JOptionPane.showMessageDialog(null, "Se hizo un pago administrativo");
            }
        }
         */
        if (nombrepr.getText().equals("") && apellidoemp.getText().equals("")) {
            prot = new Proveedor_Controlador().getProveedor(1);
            empt = new Empleado_Controlador().getEmpleado(1);
            if (pago.equals("Seleccione --")) {
                JOptionPane.showMessageDialog(null, "No ha seleccionado ninguna opcion");
            } else {
                hab.setId(0);
                hab.setProveedor(prot);
                hab.setEmpleado(empt);
                hab.setTipoBeneficiario("Administrativo");
                hab.setTipoPago(comboPago.getSelectedItem().toString());
                hab.setValor(Double.parseDouble(valor.getText()));
                hab.setDetalle(detalle.getText());
                Haber_Controlador habC = new Haber_Controlador();
                habC.crear(hab);
                System.out.println("Resultado de Empleado");
                System.out.println(nombremp.getText());
                System.out.println("Resultado de Proveedor");
                System.out.println(nombrepr.getText());
                limpiar();
                JOptionPane.showMessageDialog(null, "Se hizo un pago administrativo");
            }
            
        }else if (apellidoemp.getText().equals("")) {
            pro = new Proveedor_Controlador().getProveedor(new Controlador_All().id_perP(rucpr.getText()));
            if (pago.equals("Seleccione --")) {
                JOptionPane.showMessageDialog(null, "No ha seleccionado ninguna opcion");
            } else {
                hab.setProveedor(pro);
                hab.setEmpleado(empt);
                hab.setId(0);
                hab.setTipoBeneficiario("Proveedor");
                hab.setTipoPago(comboPago.getSelectedItem().toString());
                hab.setValor(Double.parseDouble(valor.getText()));
                hab.setDetalle(detalle.getText());
                Haber_Controlador habC = new Haber_Controlador();
                habC.crear(hab);
                System.out.println("Resultado de Empleado");
                System.out.println(nombremp.getText());
                System.out.println("*********RESULTADO DE EMPLEADO**********");
                System.out.println(empt);
                limpiar();
                JOptionPane.showMessageDialog(null, "Se hizo un pago a un proveedor");
            }

        }else if (nombrepr.getText().equals("")) {
            emp = new Empleado_Controlador().getEmpleado(new Controlador_All().id_perEC(codigoemp.getText()));
            if (pago.equals("Seleccione --")) {
                JOptionPane.showMessageDialog(null, "No ha seleccionado ninguna opcion");
            } else { 
                hab.setEmpleado(emp);
                hab.setProveedor(prot);
                hab.setId(0);
                hab.setTipoBeneficiario("Empleado");
                hab.setTipoPago(comboPago.getSelectedItem().toString());
                hab.setValor(Double.parseDouble(valor.getText()));
                hab.setDetalle(detalle.getText());
                Haber_Controlador habC = new Haber_Controlador();
                habC.crear(hab);
                System.out.println("Resultado de Proveedor");
                System.out.println(nombrepr.getText());
                System.out.println("*********RESULTADO DE PROVEEDOR**********");
                System.out.println(empt);
                System.out.println("Hola");
                limpiar();
                JOptionPane.showMessageDialog(null, "Se hizo pago a un empleado");
            }
            txHaber.setModel(new Tabla_Haber(new Controlador_All().reflejarHaber()));
        }
    }//GEN-LAST:event_jToggleButton3ActionPerformed

    private void comboPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboPagoActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_comboPagoActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel administrativo;
    private javax.swing.JLabel apellidoemp;
    private javax.swing.JLabel apellidopr;
    private javax.swing.JLabel codigoemp;
    private javax.swing.JComboBox<String> comboPago;
    private javax.swing.JTextField detalle;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JLabel nombremp;
    private javax.swing.JLabel nombrepr;
    private javax.swing.JLabel rucpr;
    private javax.swing.JTable txHaber;
    private javax.swing.JTextField valor;
    // End of variables declaration//GEN-END:variables

    private void limpiar() {
        rucpr.setText("");
        nombrepr.setText("");
        apellidopr.setText("");
        codigoemp.setText("");
        nombremp.setText("");
        apellidoemp.setText("");
        valor.setText("");
        detalle.setText("");
        comboPago.setSelectedIndex(0);
    }

}
